modLoader="javafml"
loaderVersion="[32,)"
license="GPL3"

[[mods]]
modId="tac"
version="0.3.5.2"
displayName="Timeless and Classics Guns"
updateJSONURL="https://ClumsyAlien.github.io/TaC_Patch_notes/update.json"
displayURL=""
authors="Timeless Development Team"
description='''
'''

[[dependencies.tac]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tac]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tac]]
    modId="framework"
    mandatory=true
    versionRange="[0.2.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tac]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.2-5.0.9.0,)"
    ordering="NONE"
    side="BOTH"
